#This workflow validates, deploys, and runs the specified bundle
#within a production target named "prod".

name: 'Production deployment'

#Ensure that only a single job or workflow using the same concurrency group
#runs at a time.

concurrency: 1
#Trigger this workflow whenever a pull request is pushed to the repo's
#main branch.
on:
    push:
        branches:
            - main
            - dev
        paths:
            - 'bakehouse_analytics/**'

jobs:
    deploy:
        name: 'Deploy bundle'
        runs-on: ubuntu-latest

        steps:
          #check out this repo, so that this workflow can access it.
          - uses: actions/checkout@v3

          #download the databricks CLI.
          #see https://github.com/databricks/setup-cli
          - uses: databricks/setup-cli@main

          #Set environment based on branch
          - name: Set environment
            id: set-env
            run: |
              if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                echo "env=prod" >> $GITHUB_OUTPUT
              elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
                echo "env=dev" >> $GITHUB_OUTPUT
              fi

          #deploy the bundle to prod target as defined
          #in the bundle setting file 
          - run: databricks bundle deploy
            working-directory: bakehouse_analytics
            env: 
                DATABRICKS_TOKEN: ${{secrets.DB_TOKEN}}
                DATABRICKS_BUNDLE_ENV: ${{ steps.set-env.outputs.env }}
